name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: npm

      - run: npm install --legacy-peer-deps

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - run: npx eas-cli build --platform android --profile preview --local --output app.apk
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: APK
          path: app.apk
